# Generate body-paper tables (worker, firm, origin/destination) as .tex fragments
# Replaces the Stata pipeline (comp_table_202402_LE.do) — builds directly from CSV.
#
# - Table 1 (worker outcomes): individual outcomes from S2 (Export_20260423)
# - Table 2 (firm outcomes):   firm outcomes from S1 (Export_20260331)
# - Table 3 (origin/dest):     cross-section from S1 tbl2-origin_destination
#
# Output: EJ_R1/tables-2026/{comprehensivetable,new}/
# See PLOTTING_STRATEGY.md (in Export_20260423/updated_scripts/) for the rationale.

suppressPackageStartupMessages({
  library(tidyverse)
  library(readr)
})

# Paths --------------------------------------------------------------------
path_S1   <- "/Users/clementmalgouyres/Library/CloudStorage/Dropbox/Layoff/00_ExportsCASD/Export_20260331"
path_S2   <- "/Users/clementmalgouyres/Library/CloudStorage/Dropbox/Layoff/00_ExportsCASD/Export_20260423"
out_root  <- "/Users/clementmalgouyres/Library/CloudStorage/Dropbox/Applications/Overleaf/JobDisplacement/EJ_R1/tables-2026"
out_comp  <- file.path(out_root, "comprehensivetable")
out_new   <- file.path(out_root, "new")
dir.create(out_comp, showWarnings = FALSE, recursive = TRUE)
dir.create(out_new,  showWarnings = FALSE, recursive = TRUE)

# Loader (mirrors main_plots_2026-04_body.R) -------------------------------
load_event_studies <- function(path_sortie, sub){
  files <- list.files(file.path(path_sortie, sub), full.names = TRUE,
                      pattern = "\\.csv$")
  ES <- map_df(files, read_csv, show_col_types = FALSE)
  if ("treatment_path" %in% names(ES)) ES <- filter(ES, treatment_path)
  ES
}

# Formatting helpers -------------------------------------------------------
fmt3 <- function(x) ifelse(is.na(x), "", sprintf("%.3f", x))
fmt_paren3 <- function(x) ifelse(is.na(x), "", sprintf("(%.3f)", x))
fmt_int_comma <- function(x) ifelse(is.na(x), "", formatC(round(x), format = "d", big.mark = ","))
fmt_paren_int_comma <- function(x) ifelse(is.na(x), "", paste0("(", formatC(round(x), format = "d", big.mark = ","), ")"))

# Load datasets ------------------------------------------------------------
ES_S1_main <- load_event_studies(path_S1, "event_studies-main_samples")
ES_S2_main <- load_event_studies(path_S2, "event_studies-main_samples")
ES_S1_elec <- load_event_studies(path_S1, "event_studies-elec_samples")

# Helper: pull (beta, se) for given dep_var across distances 0..5 ----------
get_es <- function(DF, dep, samp, distances = 0:5){
  DF |>
    filter(sample == samp,
           dep_var == dep,
           interaction_group == "none",
           is.na(description)) |>
    select(distance, beta, std_error) |>
    distinct() |>
    complete(distance = distances) |>
    arrange(distance) |>
    filter(distance %in% distances)
}

# =========================================================================
# TABLE 1 — Worker outcomes (S2 main)
# =========================================================================
# Cols: (1) Employed, (2) Earnings (level), (3) Log Earnings, (4) Log Hours,
#       (5) Log Hourly wage, (6) Firm wage Premium, (7) Ratio (6)/(5)
samp_w <- "le5_panelsize0"
employed   <- get_es(ES_S2_main, "employed",      samp_w)
sbr_lvl    <- get_es(ES_S2_main, "sbr",           samp_w)
lnsbr      <- get_es(ES_S2_main, "lnsbr",         samp_w)
lnnbheur   <- get_es(ES_S2_main, "lnnbheur",      samp_w)
lnsbrhour  <- get_es(ES_S2_main, "lnsbrhour",     samp_w)
fe_le      <- get_es(ES_S1_main, "fe0215_mlo_le", samp_w)  # firm outcome → S1

worker_lines <- character()
for (d in 0:5) {
  c1  <- fmt3(employed$beta[employed$distance == d])
  s1  <- fmt_paren3(employed$std_error[employed$distance == d])
  c2  <- fmt_int_comma(sbr_lvl$beta[sbr_lvl$distance == d])
  s2  <- fmt_paren_int_comma(sbr_lvl$std_error[sbr_lvl$distance == d])
  c3  <- fmt3(lnsbr$beta[lnsbr$distance == d])
  s3  <- fmt_paren3(lnsbr$std_error[lnsbr$distance == d])
  c4  <- fmt3(lnnbheur$beta[lnnbheur$distance == d])
  s4  <- fmt_paren3(lnnbheur$std_error[lnnbheur$distance == d])
  c5  <- fmt3(lnsbrhour$beta[lnsbrhour$distance == d])
  s5  <- fmt_paren3(lnsbrhour$std_error[lnsbrhour$distance == d])
  c6  <- fmt3(fe_le$beta[fe_le$distance == d])
  s6  <- fmt_paren3(fe_le$std_error[fe_le$distance == d])
  bAKM <- fe_le$beta[fe_le$distance == d]
  bHW  <- lnsbrhour$beta[lnsbrhour$distance == d]
  c7   <- if (length(bAKM) && length(bHW) && !is.na(bAKM) && !is.na(bHW) && bHW != 0) sprintf("%.3f", bAKM / bHW) else ""

  worker_lines <- c(worker_lines,
    sprintf("$ d = %d $ &%s&%s&%s&%s&%s&%s&%s\\\\", d, c1, c2, c3, c4, c5, c6, c7),
    sprintf("&%s&%s&%s&%s&%s&%s&\\\\", s1, s2, s3, s4, s5, s6))
}

worker_tex <- c(
  "% Generated by main_tables_2026-04_body.R from CASD CSV exports (Sortie 2 / Sortie 1).",
  "% Worker outcomes from Export_20260423; firm wage premium from Export_20260331.",
  "",
  "& \\multicolumn{2}{l}{Outcome in levels} & \\multicolumn{5}{l}{Outcomes in log} \\\\ \\cmidrule[1.5pt](lr){2-3} \\cmidrule[1.5pt](lr){4-8}",
  "&(1)&(2)&(3)&(4)&(5)&(6)&(7)\\\\",
  "Time to displ.&Employed&Earnings&Earnings&Hours&Hourly wage& Premium &Ratio (6)/(5)\\\\ \\midrule",
  worker_lines
)
writeLines(worker_tex, file.path(out_comp, "table_worker_body_202402.tex"))
cat("Wrote: ", file.path(out_comp, "table_worker_body_202402.tex"), "\n", sep = "")

# =========================================================================
# TABLE 2 — Firm outcomes (S1 main + elec/acco samples)
# =========================================================================
# Cols: (1) Productivity (prod_res_ma3), (2) VA/worker (ln_apl_ma3),
#       (3) Labor share (ln_lshare_ma3), (4) Wage Agreement, (5) Election turnout
samp_f <- "le5_panelsize0"
prod    <- get_es(ES_S1_main, "prod_res_ma3", samp_f)
apl     <- get_es(ES_S1_main, "ln_apl_ma3",   samp_f)
lshare  <- get_es(ES_S1_main, "ln_lshare_ma3", samp_f)
acco    <- get_es(ES_S1_elec, "wage_agreement_ind_07_alt", "le5_panelsize0-acco_alt")
elec    <- get_es(ES_S1_elec, "participation_siren0912",   "le5_panelsize0-election")

firm_lines <- character()
for (d in 0:5) {
  c1 <- fmt3(prod$beta[prod$distance == d]);     s1 <- fmt_paren3(prod$std_error[prod$distance == d])
  c2 <- fmt3(apl$beta[apl$distance == d]);       s2 <- fmt_paren3(apl$std_error[apl$distance == d])
  c3 <- fmt3(lshare$beta[lshare$distance == d]); s3 <- fmt_paren3(lshare$std_error[lshare$distance == d])
  c4 <- fmt3(acco$beta[acco$distance == d]);     s4 <- fmt_paren3(acco$std_error[acco$distance == d])
  c5 <- fmt3(elec$beta[elec$distance == d]);     s5 <- fmt_paren3(elec$std_error[elec$distance == d])
  firm_lines <- c(firm_lines,
    sprintf("$ d = %d $ &%s&%s&%s&%s&%s\\\\", d, c1, c2, c3, c4, c5),
    sprintf("&%s&%s&%s&%s&%s\\\\", s1, s2, s3, s4, s5))
}

firm_tex <- c(
  "% Generated by main_tables_2026-04_body.R from CASD CSV exports (Sortie 1).",
  "% Firm outcomes (prod_res_ma3, ln_apl_ma3, ln_lshare_ma3) from Export_20260331.",
  "% Negotiation variables (wage_agreement_ind_07_alt, participation_siren0912) from Export_20260331.",
  "",
  "& \\multicolumn{3}{l}{Firm outcomes} & \\multicolumn{2}{l}{Negotiation variables} \\\\ \\cmidrule[1.5pt](lr){2-4} \\cmidrule[1.5pt](lr){5-6}",
  "&(1)&(2)&(3)&(4)&(5)\\\\",
  "Time to displ.&Productivity&VA / Worker&Labor share&Wage Agreement&Election turnout\\\\ \\midrule",
  firm_lines
)
writeLines(firm_tex, file.path(out_comp, "table_firm_body_202402.tex"))
cat("Wrote: ", file.path(out_comp, "table_firm_body_202402.tex"), "\n", sep = "")

# -------------------------------------------------------------------------
# Robustness: Table 1 firm panel using fixed 2002–2015 accounting averages
#  (_mean_0215) instead of 3-year moving average (_ma3).
# Each firm gets a single time-invariant productivity/VA/labor share value
# averaged over 2002–2015; event-study captures cross-firm reallocation only.
# -------------------------------------------------------------------------
prod0215   <- get_es(ES_S1_main, "prod_res_mean_0215",  samp_f)
apl0215    <- get_es(ES_S1_main, "ln_apl_mean_0215",    samp_f)
lshare0215 <- get_es(ES_S1_main, "ln_lshare_mean_0215", samp_f)

firm_lines_0215 <- character()
for (d in 0:5) {
  c1 <- fmt3(prod0215$beta[prod0215$distance == d])
  s1 <- fmt_paren3(prod0215$std_error[prod0215$distance == d])
  c2 <- fmt3(apl0215$beta[apl0215$distance == d])
  s2 <- fmt_paren3(apl0215$std_error[apl0215$distance == d])
  c3 <- fmt3(lshare0215$beta[lshare0215$distance == d])
  s3 <- fmt_paren3(lshare0215$std_error[lshare0215$distance == d])
  c4 <- fmt3(acco$beta[acco$distance == d])
  s4 <- fmt_paren3(acco$std_error[acco$distance == d])
  c5 <- fmt3(elec$beta[elec$distance == d])
  s5 <- fmt_paren3(elec$std_error[elec$distance == d])
  firm_lines_0215 <- c(firm_lines_0215,
    sprintf("$ d = %d $ &%s&%s&%s&%s&%s\\\\", d, c1, c2, c3, c4, c5),
    sprintf("&%s&%s&%s&%s&%s\\\\", s1, s2, s3, s4, s5))
}

firm_tex_0215 <- c(
  "% Generated by main_tables_2026-04_body.R from CASD CSV exports (Sortie 1).",
  "% Robustness — firm outcomes averaged over 2002-2015 (fixed long window):",
  "%   prod_res_mean_0215, ln_apl_mean_0215, ln_lshare_mean_0215.",
  "% Negotiation outcomes (wage agreement, election turnout) unchanged.",
  "",
  "& \\multicolumn{3}{l}{Firm outcomes (2002--2015 averages)} & \\multicolumn{2}{l}{Negotiation variables} \\\\ \\cmidrule[1.5pt](lr){2-4} \\cmidrule[1.5pt](lr){5-6}",
  "&(1)&(2)&(3)&(4)&(5)\\\\",
  "Time to displ.&Productivity&VA / Worker&Labor share&Wage Agreement&Election turnout\\\\ \\midrule",
  firm_lines_0215
)
writeLines(firm_tex_0215,
           file.path(out_comp, "table_firm_body_202402_mean_0215.tex"))
cat("Wrote: ",
    file.path(out_comp, "table_firm_body_202402_mean_0215.tex"), "\n",
    sep = "")

# =========================================================================
# TABLE 3 — Origin/Destination cross-section (S1)
# =========================================================================
TBL2 <- read_csv(file.path(path_S1, "tbl2-origin_destination",
                            "tbl2-le5_panelsize0-fixed_all.csv"),
                  show_col_types = FALSE)

# Star helper (estout convention used in original tex: * 0.05, ** 0.01, *** 0.001)
star <- function(p){
  if (is.na(p)) return("")
  if (p < 0.001) "\\sym{***}"
  else if (p < 0.01) "\\sym{**}"
  else if (p < 0.05) "\\sym{*}"
  else ""
}

# Spec column mapping: (dep_var, controls, naf2_fe). All weighted = FALSE.
# Columns without sector FE (the original cols 1-3) are dropped to keep the
# table compact — the sector-FE specs are the primary read.
specs <- tribble(
  ~col, ~label,           ~dep_var,             ~controls, ~naf2_fe,
  1,    "Wage premium",   "fe0215_mlo_le",      FALSE,     TRUE,
  2,    "VA/worker",      "ln_apl_mean_0215",   FALSE,     TRUE,
  3,    "Productivity",   "prod_res_mean_0215", FALSE,     TRUE,
  4,    "Wage premium",   "fe0215_mlo_le",      TRUE,      FALSE,
  5,    "Wage premium",   "fe0215_mlo_le",      TRUE,      TRUE
)

get_cell <- function(spec_dep, spec_ctrl, spec_naf, var, spec_weighted = FALSE){
  TBL2 |>
    filter(dep_var == spec_dep,
           controls == spec_ctrl,
           naf2_fe == spec_naf,
           weighted == spec_weighted,
           variable == var) |>
    slice(1)
}

# Format coef + tval for the destination/origin/control rows
fmt_coef <- function(b, p) sprintf("%10.4g%s", b, star(p))
fmt_tval <- function(t)   sprintf("(%5.2f)", t)

# Build columns
build_col <- function(spec, weighted_flag = FALSE){
  d_row <- get_cell(spec$dep_var, spec$controls, spec$naf2_fe, "destinationTRUE", weighted_flag)
  o_row <- get_cell(spec$dep_var, spec$controls, spec$naf2_fe, "originTRUE", weighted_flag)

  if (spec$controls){
    apl_row <- get_cell(spec$dep_var, spec$controls, spec$naf2_fe, "ln_apl_mean_0215", weighted_flag)
    emp_row <- get_cell(spec$dep_var, spec$controls, spec$naf2_fe, "ln_emp_mean_0215", weighted_flag)
  } else {
    apl_row <- tibble(beta = NA, tval = NA, pval = NA)
    emp_row <- tibble(beta = NA, tval = NA, pval = NA)
  }

  # P-value of equality test origin == destination, conservative (independent SE)
  z_val <- (o_row$beta - d_row$beta) / sqrt(o_row$std_error^2 + d_row$std_error^2)
  p_eq  <- 2 * (1 - pnorm(abs(z_val)))

  list(
    dest_b   = fmt_coef(d_row$beta, d_row$pval),
    dest_t   = fmt_tval(d_row$tval),
    orig_b   = fmt_coef(o_row$beta, o_row$pval),
    orig_t   = fmt_tval(o_row$tval),
    apl_b    = if (is.na(apl_row$beta)) "" else fmt_coef(apl_row$beta, apl_row$pval),
    apl_t    = if (is.na(apl_row$tval)) "" else fmt_tval(apl_row$tval),
    emp_b    = if (is.na(emp_row$beta)) "" else fmt_coef(emp_row$beta, emp_row$pval),
    emp_t    = if (is.na(emp_row$tval)) "" else fmt_tval(emp_row$tval),
    n_obs    = d_row$n_obs,
    r2       = d_row$r2,
    sec_fe   = if (spec$naf2_fe) "$\\surd $" else "",
    p_eq     = sprintf("%.3f", p_eq)
  )
}

# Pad function: estout uses width-aligned cells. We'll pad to 12 chars right-aligned for numbers.
pad <- function(x, w = 12){
  s <- as.character(x)
  if (nchar(s) < w) paste0(strrep(" ", w - nchar(s)), s) else s
}
cell <- function(x, full_w = 21){
  s <- as.character(x)
  if (nchar(s) >= full_w) s else paste0(s, strrep(" ", full_w - nchar(s)))
}

build_row <- function(values, leader, full_w = 21){
  vals <- map_chr(values, \(v) cell(v, full_w))
  paste0(cell(leader, 20), "&", paste(vals, collapse = "&"), "\\\\")
}

write_tbl2 <- function(weighted_flag, out_filename, regression_label, specs_use = specs){
  cols <- map(seq_len(nrow(specs_use)), \(i) build_col(specs_use[i, ], weighted_flag = weighted_flag))

  header1 <- paste0(strrep(" ", 20), "&",
    paste(map_chr(seq_len(nrow(specs_use)), \(i) cell(sprintf("\\multicolumn{1}{c}{(%d)}", i), 21)), collapse = "&"),
    "\\\\")
  header2 <- paste0(strrep(" ", 20), "&",
    paste(map_chr(seq_len(nrow(specs_use)), \(i) cell(sprintf("\\multicolumn{1}{c}{%s}", specs_use$label[i]), 21)), collapse = "&"),
    "\\\\")

  row_dest_b <- build_row(map_chr(cols, \(c) c$dest_b), "Destination firm")
  row_dest_t <- build_row(map_chr(cols, \(c) c$dest_t), "")
  row_orig_b <- build_row(map_chr(cols, \(c) c$orig_b), "Origin firm")
  row_orig_t <- build_row(map_chr(cols, \(c) c$orig_t), "")
  row_apl_b  <- build_row(map_chr(cols, \(c) c$apl_b),  "VA/worker")
  row_apl_t  <- build_row(map_chr(cols, \(c) c$apl_t),  "")
  row_emp_b  <- build_row(map_chr(cols, \(c) c$emp_b),  "Employees")
  row_emp_t  <- build_row(map_chr(cols, \(c) c$emp_t),  "")

  row_n      <- build_row(map_chr(cols, \(c) formatC(c$n_obs, format = "d")), "Observations")
  row_r2     <- build_row(map_chr(cols, \(c) sprintf("%.3f", c$r2)), "\\(R^{2}\\)")
  row_ar2    <- build_row(map_chr(cols, \(c) sprintf("%.3f", c$r2)), "Adjusted \\(R^{2}\\)")
  row_sec    <- build_row(map_chr(cols, \(c) c$sec_fe), "Sector FE")
  row_peq    <- build_row(map_chr(cols, \(c) c$p_eq), "P-value Origin-Destination")

  has_controls <- any(specs_use$controls)
  body <- if (has_controls) {
    c(row_dest_b, row_dest_t, "\\addlinespace",
      row_orig_b, row_orig_t, "\\addlinespace",
      row_apl_b,  row_apl_t,  "\\addlinespace",
      row_emp_b,  row_emp_t)
  } else {
    c(row_dest_b, row_dest_t, "\\addlinespace",
      row_orig_b, row_orig_t)
  }

  t3 <- c(
    paste0("% Generated by main_tables_2026-04_body.R from CASD CSV exports (Sortie 1)."),
    paste0("% tbl2-le5_panelsize0-fixed_all.csv (", regression_label, ")."),
    "% P-value of Origin-Destination equality is computed assuming independent SE",
    "% (conservative); CSV does not export the joint covariance.",
    "",
    header1, header2, "\\midrule",
    body,
    "\\midrule",
    row_n, row_r2, row_ar2, row_sec, row_peq
  )
  writeLines(t3, file.path(out_new, out_filename))
  cat("Wrote: ", file.path(out_new, out_filename), "\n", sep = "")
}

write_tbl2(weighted_flag = FALSE,
           out_filename = "desc_regression_hiring_firing_LE__all_202402.tex",
           regression_label = "unweighted regressions")
# Weighted version (worker-level analogue): only the 3 base columns are
# available; the controls=TRUE specs (cols 4-5) were not run on the weighted
# regressions in CASD. We therefore drop them.
specs_weighted <- specs |> filter(!controls)
write_tbl2(weighted_flag = TRUE,
           out_filename = "desc_regression_hiring_firing_LE__weighted_202402.tex",
           regression_label = "weighted by firm employment, worker-level analogue",
           specs_use = specs_weighted)

# =========================================================================
# TABLE A.X — Raw firm-level means by group (origin / destination / pop)
# =========================================================================
# Source: means-le5_panelsize0-fixed_all.csv (S1). Four rows of cell means
# indexed by (origin, destination) in {FALSE, TRUE}^2. We aggregate the
# four cells to three exhaustive groups: Population (origin == FALSE
# AND destination == FALSE), Origin firms (origin == TRUE), Destination
# firms (destination == TRUE). The "Both" cell (n=497) appears in both
# the Origin and Destination rows -- a negligible 3.5% of origins and
# 9.7% of destinations -- so the rows still admit the descriptive
# interpretation. Group-level means are weighted averages of the cell
# means using n_siren as the weight.
MEANS <- read_csv(file.path(path_S1, "tbl2-origin_destination",
                             "means-le5_panelsize0-fixed_all.csv"),
                   show_col_types = FALSE)

mean_cols <- c("fe0215_mlo_le", "ln_apl_mean_0215", "prod_res_mean_0215",
               "ln_lshare_mean_0215", "ln_emp_mean_0215")

agg_group <- function(rows){
  w    <- rows$n_siren
  out  <- vapply(mean_cols, \(v) weighted.mean(rows[[v]], w, na.rm = TRUE),
                 numeric(1))
  c(out, n_siren = sum(w))
}

means_pop  <- agg_group(MEANS[!MEANS$origin & !MEANS$destination, ])
means_org  <- agg_group(MEANS[ MEANS$origin                     , ])
means_dst  <- agg_group(MEANS[ MEANS$destination                , ])

format_n <- function(n) formatC(round(n), big.mark = ",", format = "d")
format_x <- function(x) sprintf("%.3f", x)
format_y <- function(x) formatC(round(x), big.mark = ",", format = "d")  # year

row <- function(label, vec){
  paste0(
    label, " & ",
    format_x(vec["fe0215_mlo_le"]),       " & ",
    format_x(vec["ln_apl_mean_0215"]),    " & ",
    format_x(vec["prod_res_mean_0215"]),  " & ",
    format_x(vec["ln_lshare_mean_0215"]), " & ",
    format_x(vec["ln_emp_mean_0215"]),    " & ",
    format_n(vec["n_siren"]),             " \\\\"
  )
}

means_tex <- c(
  "% Generated by main_tables_2026-04_body.R from CASD CSV (Sortie 1).",
  "% means-le5_panelsize0-fixed_all.csv (raw cell means, aggregated to",
  "% Population / Origin / Destination groups, weighted by n_siren).",
  "",
  "                & \\multicolumn{1}{c}{(1)} & \\multicolumn{1}{c}{(2)} & \\multicolumn{1}{c}{(3)} & \\multicolumn{1}{c}{(4)} & \\multicolumn{1}{c}{(5)} & \\multicolumn{1}{c}{(6)} \\\\",
  "                & \\multicolumn{1}{c}{Wage premium} & \\multicolumn{1}{c}{ln(VA/L)} & \\multicolumn{1}{c}{Productivity} & \\multicolumn{1}{c}{ln(labor share)} & \\multicolumn{1}{c}{ln(L)} & \\multicolumn{1}{c}{N (firms)} \\\\",
  "\\midrule",
  row("Population (neither origin nor destination)", means_pop),
  row("Origin firms",                                means_org),
  row("Destination firms",                           means_dst)
)

writeLines(means_tex,
           file.path(out_new, "desc_means_origin_destination_LE_2026-05.tex"))
cat("Wrote: ",
    file.path(out_new, "desc_means_origin_destination_LE_2026-05.tex"), "\n",
    sep = "")

cat("Done.\n")
