# Regenerate the MLO descriptive matching-balance tables for the EJ R1
# revision (MLO30 sample = panelpanSIZE2). Produces:
#
#   EJ_R1/tables-2026/MLOAllmatchvar_2026-05.tex   (matching variables)
#
# Source: misc-descriptive_statistics/matching_balance.csv from CASD export
# Export_20260331 (S1 and S2 give identical numbers for these vars).
#
# Replaces the legacy MLOAllmatchvar_20210908.tex which was generated by
# Z_Analysis/8_2021/Export0807/1_Desc.do on the OLD MLO_PanelSIZE2.dta
# (MLO90, 90% loss threshold) and ended up incorrectly inserted in
# EJ_R1/tables-2026/ during a copy-batch on 2026-04-28.
#
# Note: the original tex had a bottom row "Events". The matching_balance
# CSV does not export the count of distinct firm-x-year mass-layoff
# events. We therefore omit "Events" and report "Obs (workers)" instead.
# A separate CASD aggregation can add the events count later.

library(tidyverse)
library(readr)

path_S1 <- "/Users/clementmalgouyres/Library/CloudStorage/Dropbox/Layoff/00_ExportsCASD/Export_20260331"
out_dir <- "/Users/clementmalgouyres/Library/CloudStorage/Dropbox/Applications/Overleaf/JobDisplacement/EJ_R1/tables-2026"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

bal <- read_csv(file.path(path_S1, "misc-descriptive_statistics/matching_balance.csv"),
                show_col_types = FALSE)

# Distinct origin firms (proxy for the firm-year events count).
# Source: tbl2-origin_destination/means-<sample>-fixed_all.csv from the same
# CASD export. n_distinct(sir) summed over origin=TRUE rows gives the count
# of distinct firms in the AKM-eligible panel that ever served as the origin
# of a displacement in the sample period. For these samples this is close
# but not strictly equal to the count of distinct (firm, year) layoff events
# (a firm with layoffs in multiple years counts once).
get_origin_firms <- function(sample_name, export_root) {
  f <- file.path(export_root,
                 "tbl2-origin_destination",
                 paste0("means-", sample_name, "-fixed_all.csv"))
  d <- read_csv(f, show_col_types = FALSE)
  d |> filter(origin) |> summarise(n = sum(nobs)) |> pull(n)
}

# Helpers ----
fmt_num <- function(x, digits = 2) formatC(x, format = "f", digits = digits, big.mark = ",")
fmt_sd  <- function(x, digits = 2) sprintf("(%s)", fmt_num(x, digits))
fmt_nd  <- function(x, digits = 3) sprintf("%+.3f", x)

build_row <- function(df, var_root, label, digits = 2) {
  mn <- df |> filter(name == var_root) |> slice(1)
  sd <- df |> filter(name == paste0(var_root, "_sd")) |> slice(1)
  if (nrow(mn) == 0) return(c(
    sprintf("%-30s & %s & %s & %s \\\\", label, "", "", ""),
    sprintf("%-30s & %s & %s & %s \\\\", "", "", "", "")
  ))
  c(
    sprintf("%-30s & %s & %s & %s \\\\",
            label,
            fmt_num(mn$Treated, digits),
            fmt_num(mn$Control, digits),
            fmt_nd(mn$`Norm. Diff.`)),
    sprintf("%-30s & %s & %s & %s \\\\",
            "",
            fmt_sd(sd$Treated, digits),
            fmt_sd(sd$Control, digits),
            "")
  )
}

# MLO30 = panelpanSIZE2 ----
mlo <- bal |> filter(sample == "panelpanSIZE2")
n_treated <- mlo$n_treated[1]
n_control <- mlo$n_control[1]
n_origin_firms <- get_origin_firms("panelpanSIZE2", path_S1)

rows <- c(
  build_row(mlo, "age_cl",     "Age",                              digits = 2),
  build_row(mlo, "sbrhour2",   "Hourly wage at $t^D-2$",            digits = 2),
  build_row(mlo, "sbrhour3",   "Hourly wage at $t^D-3$",            digits = 2),
  build_row(mlo, "nbheur2",    "Hours worked at $t^D-2$",           digits = 2),
  build_row(mlo, "nbheur3",    "Hours worked at $t^D-3$",           digits = 2),
  build_row(mlo, "nbsa_ent1",  "\\# employees at firm at $t^D-1$",  digits = 1)
)

tex <- c(
  "% Generated by main_tables_2026-04_descriptives_mlo.R",
  "% Source: matching_balance.csv from CASD export Export_20260331,",
  "% sample = panelpanSIZE2 (MLO30: firms with empclos >= 10 in t-1 and",
  "% Picart-corrected employment loss between t-1 and t).",
  "% This file replaces the stale MLOAllmatchvar_20210908.tex.",
  "{",
  "\\def\\sym#1{\\ifmmode^{#1}\\else\\(^{#1}\\)\\fi}",
  "\\begin{tabular}{l*{3}{c}}",
  "\\hline\\hline",
  "            & \\multicolumn{1}{c}{(1)} & \\multicolumn{1}{c}{(2)} & \\multicolumn{1}{c}{(3)} \\\\",
  "            & \\multicolumn{1}{c}{MLO30} & \\multicolumn{1}{c}{Control} & \\multicolumn{1}{c}{Norm.\\ Diff.} \\\\",
  "\\hline",
  rows,
  "\\hline",
  sprintf("Obs (workers)              & %s & %s & %s \\\\",
          formatC(n_treated, format = "d", big.mark = ","),
          formatC(n_control, format = "d", big.mark = ","),
          formatC(n_treated + n_control, format = "d", big.mark = ",")),
  sprintf("Distinct origin firms      & %s &        &        \\\\",
          formatC(n_origin_firms, format = "d", big.mark = ",")),
  "\\hline\\hline",
  "\\end{tabular}",
  "}"
)

out <- file.path(out_dir, "MLOAllmatchvar_2026-05.tex")
writeLines(tex, out)
cat("Wrote:", out, "\n")

# ============================================================
# Quantivar table (variables not used in matching)
# Replaces MLOAllquantivar_20210908.tex
# Variables (matching the legacy table):
#   Gender Male (sx)
#   Annual gross earnings (sbr at d=-2 from event_studies-main_samples)
#   Firm-wage premium fe0215_mlo_le (formerly fe0115)
# ============================================================

# Pull annual gross earnings (sbr) at d=-2 from S2 event-studies
# (S2 is correct here: worker-level outcome, treatment_path == TRUE)
es_path <- "/Users/clementmalgouyres/Library/CloudStorage/Dropbox/Layoff/00_ExportsCASD/Export_20260423/event_studies-main_samples/panelpanSIZE2-res.csv"
es <- read_csv(es_path, show_col_types = FALSE)
sbr_dm2 <- es |>
  filter(treatment_path,
         interaction_group == "none",
         is.na(description),
         dep_var == "sbr",
         distance == -2) |>
  slice(1)

# Helper for the quantivar table -- handles missing SD gracefully
build_row_q <- function(df, var_root, label, digits = 2,
                        treated_mean = NULL, control_mean = NULL,
                        nd = NULL, treated_sd = NULL, control_sd = NULL) {
  # If explicit means are passed, use them; otherwise look up in df.
  if (is.null(treated_mean)) {
    mn <- df |> filter(name == var_root) |> slice(1)
    treated_mean <- mn$Treated
    control_mean <- mn$Control
    nd           <- mn$`Norm. Diff.`
  }
  if (is.null(treated_sd)) {
    sd_row <- df |> filter(name == paste0(var_root, "_sd")) |> slice(1)
    treated_sd <- if (nrow(sd_row) > 0) sd_row$Treated else NA_real_
    control_sd <- if (nrow(sd_row) > 0) sd_row$Control else NA_real_
  }

  fmt_sd_or_dash <- function(x) if (is.na(x)) "--" else fmt_sd(x, digits)

  c(
    sprintf("%-50s & %s & %s & %s \\\\",
            label,
            fmt_num(treated_mean, digits),
            fmt_num(control_mean, digits),
            if (is.na(nd)) "--" else fmt_nd(nd)),
    sprintf("%-50s & %s & %s & %s \\\\",
            "",
            fmt_sd_or_dash(treated_sd),
            fmt_sd_or_dash(control_sd),
            "")
  )
}

# Annual gross earnings (sbr): we have mean from event-study CSV but not SD
# (matching_balance.csv does not export sbr; event-study CSV has only means).
# Compute Imbens-Rubin norm. diff. is impossible without SDs, so report --.
sbr_treated_mean <- sbr_dm2$mean_treated
sbr_control_mean <- sbr_dm2$mean_control

rows_q <- c(
  build_row_q(mlo, "sx",                       "Gender: Male",                                      digits = 2),
  build_row_q(mlo, "sbr_at_dm2",               "Annual gross earnings at $t^D-2$",                  digits = 2,
              treated_mean = sbr_treated_mean,
              control_mean = sbr_control_mean,
              nd = NA_real_,
              treated_sd = NA_real_,
              control_sd = NA_real_),
  build_row_q(mlo, "fe0215_mlo_le",            "Firm wage premium $\\widehat{\\psi}_{J(i,t)}$",      digits = 2),
  build_row_q(mlo, "hhi_comp_sirze_eqtp_ma3",  "Local labor market HHI",                            digits = 4),
  build_row_q(mlo, "year_cre",                 "Firm year of creation",                             digits = 1)
)

tex_q <- c(
  "% Generated by main_tables_2026-04_descriptives_mlo.R",
  "% Source: matching_balance.csv from Export_20260331",
  "% (sx, fe0215_mlo_le); event_studies-main_samples/panelpanSIZE2-res.csv",
  "% from Export_20260423 (sbr at d=-2). Sample = panelpanSIZE2 (MLO30).",
  "% Replaces the stale MLOAllquantivar_20210908.tex.",
  "%",
  "% Note: SD and Imbens-Rubin normalized difference for annual gross",
  "% earnings are not exported in either CSV; reported as '--'.",
  "{",
  "\\def\\sym#1{\\ifmmode^{#1}\\else\\(^{#1}\\)\\fi}",
  "\\begin{tabular}{l*{3}{c}}",
  "\\hline\\hline",
  "            & \\multicolumn{1}{c}{(1)} & \\multicolumn{1}{c}{(2)} & \\multicolumn{1}{c}{(3)} \\\\",
  "            & \\multicolumn{1}{c}{MLO30} & \\multicolumn{1}{c}{Control} & \\multicolumn{1}{c}{Norm.\\ Diff.} \\\\",
  "\\hline",
  rows_q,
  "\\hline",
  sprintf("Obs (workers)              & %s & %s & %s \\\\",
          formatC(n_treated, format = "d", big.mark = ","),
          formatC(n_control, format = "d", big.mark = ","),
          formatC(n_treated + n_control, format = "d", big.mark = ",")),
  sprintf("Distinct origin firms      & %s &        &        \\\\",
          formatC(n_origin_firms, format = "d", big.mark = ",")),
  "\\hline\\hline",
  "\\end{tabular}",
  "}"
)

out_q <- file.path(out_dir, "MLOAllquantivar_2026-05.tex")
writeLines(tex_q, out_q)
cat("Wrote:", out_q, "\n")
